### ISSUE TITLE
Color picking went missing after Zenity update

### ISSUE THREAD

**Issue by MeanEYE** [KabbAmine/vCoolor.vim#18]
After recent update Zenity lost its ability to pick colors from the screen. Instead it offers retarded set of limited colors he pulls out of who knows where. Either way, rendering color picker useless to me. ![2015-05-26-193830_1256x645_scrot](https://cloud.githubusercontent.com/assets/1911594/7818918/cbd1f18e-03de-11e5-854a-a77fd795f848.png)

I know this is not really _issue_ related to this plugin but I feel it's important to report it to avoid duplicates from other people and perhaps they added some sort of flag that allows us to get back to more useful color selection.

**Comment by KabbAmine** [comment]
Which version is it? Have you checked the `man` if there are a new color-selection options? I've tested with zenity 3.14.0 and it provides the same options as the old versions.

In any case, you can still use [yad](http://sourceforge.net/projects/yad-dialog/) which the plugin supports by default.

**Comment by MeanEYE** [comment]
I have version `3.16.2`. As far as I can see there are no additional options. There's `--color` and `--show-palette` flags. That's it for color selection options. _Yad_ doesn't seem to be in Debian repositories. Would it be possible to make option for plugin to execute custom command? I'd rather have simple PyGTK script that shows color picker than install something from SourceForge.

**Comment by KabbAmine** [comment]
Good idea, why not.

All the color conversion functions are in vimscript, so any color picker who accept and return a color in hexadecimal format should work (e.g [colorpicker-windows-commandline](https://github.com/jaxbot/colorpicker-windows-commandline)).

**Comment by MeanEYE** [comment]
Glad to hear that.

**Comment by KabbAmine** [comment]
@MeanEYE If you manage to make a multi-OS color picker, let me know. It will be interesting to use it as the default one in the plugin.

**Comment by MeanEYE** [comment]
Sure. I'll see if I can mash something up. If Vim is compiled with Python support we could possibly do something with wxWidgets and their color picker dialog if it has option to pick color from the screen.

**Comment by MeanEYE** [comment]
I completely forgot about this. Sorry for the delay. I'll grab some free time these days.

**Comment by KabbAmine** [comment]
There is no hurry, take your time.
