### ISSUE TITLE
<A-c> causes "ã" to open color picker.

### ISSUE THREAD

**Issue by FernandoBasso** [KabbAmine/vCoolor.vim#21]
First of all, thanks for this awesome plugin.

When I am writing text in my native lang (pt-br), and I happen to type `~` followed by `a` to produce `ã` (part of many words), the color picker opens as if I had typed `<A-c>`. I tried disabling the default mappings as suggested in the tutorial, and then added `<A-c>` as a custom mapping, and the problem persists.

If with the default mappings disabled, I map

    let g:vcoolor_disable_mappings = 1
    let g:vcoolor_map = '<F8>'

then `F8` opens the color picker and `ã` doesn't open the color picker anymore, which is the expected behavior.

I am on windows (at work, and I don't know if it will happen in my linux box at home, but I'll check it out this evening). My keyboard layout is pt-br.

**Comment by KabbAmine** [comment]
I think that both combinations share the same key code, so no way to avoid that except using another mapping for vcoolor.

If we find a way to detect the keyboard layout from vim, we could in a simple condition set a specific mapping for each layout.

**Comment by KabbAmine** [comment]
Being not related with the plugin itself, I'm closing the issue.

@FernandoBasso Feel free to open it again if needed.
