### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by ant-i-c-s** [KabbAmine/vCoolor.vim#25]
I'm using this on terminal vim in archlinux.

```
Error detected while processing function <SNR>40_VCoolIns[9]..vcoolor#convert#Hex2Rgb:
line    6:
E684: list index out of range: 0
line    7:
E684: list index out of range: 3
```

This happens on alt+r and alt+w.

When I use alt+c there is no error message but it inserts an output such as `RGB9,,1`

edit:
Even though it says there's an error in Hex2Rgb, when used on the command line e.g. `:Hex2Rgb "#FF8349"` it returns `255, 131, 73` happily.

**Comment by KabbAmine** [comment]
Unfortunately, now I don't have time to test it but I'll look into it on the next 2/3 days.

Thanks for reporting the issue.

**Comment by KabbAmine** [comment]
I cannot reproduce your issue.

Please provide me more informations:
- Vim version
- Your vcoolor configuration
- Steps to reproduce (What have you done, what do you expect).

**Comment by notantonia** [comment]
Hi!

Sorry, I forgot I was using neovim. Do you have plans to support it?

**Comment by KabbAmine** [comment]
It should logically work on neovim too, try using another mapping(s) (`alt` is handled differently on terminals), something like:

```vim
let g:vcoolor_map = 'gco'
let g:vcool_ins_rgb_map = 'gcr'
let g:vcool_ins_hsl_map = 'gch'
let g:vcool_ins_rgba_map = 'gcb'
```

Anyway, I'm planning to rewrite the plugin when I'll have time (After a few months I guess :smile: ), and then I'll be sure to test it on neovim too.

**Comment by Draiken** [comment]
I have the same error on arch linux using vim 8: https://gist.github.com/Draiken/4a49373324b39d0898b8df2f0136bd75

The mappings didn't work for me, so I tried using `VCoolIns r` and I get this error.
Note that `VCoolor` worked, but since I need the RGB format, it doesn't help me :slightly_smiling_face:

**Comment by Draiken** [comment]
When I use `VCoolor` I get a "RGB6464" string inserted. So I tested running
```
:Hex2Rgb "RGB6464"
```
and got the same error:
```Error detected while processing function vcoolor#convert#Hex2Rgb:
line    6:
E684: list index out of range: 0
line    7:
E684: list index out of range: 3
```
My guess is that the color picker is returning something other than the expected

**Comment by Draiken** [comment]
```
$ zenity --color-selection
rgb(255,255,255)
```
Not sure if zenity changed the return from the color selection, but this is what is returned for me.
This then enters the magic `strlen(s:newCol) >= 13` if clause, and sends an invalid string downstream

**Comment by KabbAmine** [comment]
Good catch @Draiken, old versions of zenity returned color in hexadecimal, and from what I've seen there are no options to enable this old behaviour in the newest versions.

So the best way before my refactoring is to install [`yad`](https://aur.archlinux.org/packages/yad/) then vCoolor will use it by default.
