### ISSUE TITLE
Make right Alt working on Mac

### ISSUE THREAD

**Issue by osenvosem** [KabbAmine/vCoolor.vim#27]
MacOS 10.12.3, iTerm 3.0.13, NeoVim 0.1.7
The combinations work with left Alt only. It would be fine if they worked with the right one also.

**Comment by KabbAmine** [comment]
Its how vim is designed, check `:h key-notation` and you'll see that there is no distinction between left/right alt.
Using alt in terminal is always problematic, and may work or not depending of the terminal.

My advice is to either remap the function to another key(s) or use something like `xmodmap` to remap right alt key to make it recognizable by vim (I personally use `alt-c` even if I'm a touch typist).

If you find a way to remap right alt, let me know, it will be interesting to add it to the readme.
Meanwhile being not related to the plugin, I close the issue. Feel free to continue the discussion here if needed.
