### ISSUE TITLE
vCoolor opens when I hit "ö"

### ISSUE THREAD

**Issue by supersambo** [KabbAmine/vCoolor.vim#29]
I'm on a german keyboard using vCoolor in vim 8 on ubuntu 16.10. Surprisingly vCoolor opens when I hit the "ö" key in insert and normal mode. Since I haven't mapped it like that I'm not sure how to disable this. 

I'm using not only for programming but also for normal writing tasks in german, which is why I really need this key to be functioning.

**Comment by KabbAmine** [comment]
It may be the same as #21 so my advice is to not use alt for vcoolor mapping.

I'm unfortunately unavailable and will not have time soon, so I'll investigate more when I can.

**Comment by supersambo** [comment]
Thank you very much for the hint!

Remapping like this
```
let g:vcoolor_disable_mappings = 1
let g:vcoolor_map = '<F8>'
````
as suggested in  #21 solved this issue for me!
