### ISSUE TITLE
Error when executing commands and when starts vim

### ISSUE THREAD

**Issue by nasserahmed96** [KabbAmine/vCoolor.vim#30]
After I have installed vCoolor manually and when I run vim it gives me the following error
`Error detected while processing /home/nasser/.vim/plugin/vCoolor.vim:
line   88:
E117: Unknown function: vcoolor#convert#HtmlBaseColName
E15: Invalid expression: vcoolor#convert#HtmlBaseColName()
Press ENTER or type command to continue
`
Anyway when I execute simple vCoolor commands in vim it also gives me an error, here is the error when typing `VCoolor`
`Error detected while processing function <SNR>10_VCoolor[4]..<SNR>10_GetCurrCol:
line   22:
E121: Undefined variable: s:colorNames
E116: Invalid arguments for function has_key(s:colorNames, tolower(l:cword))
E15: Invalid expression: has_key(s:colorNames, tolower(l:cword))
`
But it gives me the Color picker window and it works
I use Zenity on xfce4 Arch Linux

**Comment by KabbAmine** [comment]
How did you install the plugin?
And which versions of vim and zenity (`zenity --version`) did you use?

**Comment by nasserahmed96** [comment]
Sorry for being late.
I have installed it manually by adding the _vCooler.vim_ file in the _plugin_ dir .
zenity version is 3.28.1
vim 8.1

**Comment by KabbAmine** [comment]
Better late than never.

Have you added the autoload files in the appropriate directory? The 1st error clearly says that the function `vcoolor#convert#HtmlBaseColName` is not found.

Question apart, why not use the packages feature of vim 8 to manage plugins (`:h packages`) or a vim plugin manager?

**Comment by nasserahmed96** [comment]
That was the error I didn't add autoload files now every things works properly, sorry for wasting your time.
I just wanted to learn more about vim and how to add plugins to it, I'm very sorry for this mistake.

**Comment by KabbAmine** [comment]
No problem, do not hesitate to report issues/questions, that's how we learn.

But I do not advise you to add plugins manually, as I already said the proper way without plugin managers is to use the new packages feature of vim 8, see `:help packages`.

Good continuation.
