### ISSUE TITLE
Vim-Plug gives no errors and does not install

### ISSUE THREAD

**Issue by dotrosedotnet** [KabbAmine/vCoolor.vim#38]
Is there an incompatibility with NeoVim which makes it such that Vim-Plug is unaffected by the installation line in my config?

**Comment by KabbAmine** [comment]
Not that I'm aware, but note that I did not follow neither neovim or vim for the last 6-7 months, so I've maybe missed some important changes.

I will check later and report back.

**Comment by dotrosedotnet** [comment]
I got it working! No worries! I rebooted, ran PlugUpgrade, then 
PlugUpdate and it worked. Curious! Sorry to bother!

Signed,
● 🌹

**Comment by KabbAmine** [comment]
Good to know :relaxed:

A better way to automatically apply the changes is to source your vim configuration after each modification/save, either automatically with an autocmd or with the command `:source`.
