### ISSUE TITLE
Default bindings did not work for me

### ISSUE THREAD

**Issue by rebuilt** [KabbAmine/vCoolor.vim#39]
I was able to find a workaround but the default keybinding does not trigger anything. 

The output of ```:verbose imap <A-c> ```
is                   ``` <Esc>:VCoolor<CR>a```

So the mapping exists.

When I entered the command ```:VCoolor ```, the color picker was launched and worked correctly.
I edited these lines into my .vimrc and got it to work.  I was not able to use any key combination involving the ALT key so I used leader instead.  

```let g:vcoolor_disable_mappings = 1```
```nnoremap <leader>c <Esc>:VCoolor<CR>a```

I'm not sure if this issue is specific to my os, or my vim configuration, or my keyboard.  Ubuntu 18.04.3 LTS, VIM 8.1, keyboard - US - English with Capslock disabled via toggle switch.

**Comment by rebuilt** [comment]
Ok, I got the default bindings to work by adding this code to my .vimrc
```execute "set <A-c>=\ec"```

**Comment by KabbAmine** [comment]
Alt by default may work or not depending on the used terminal, so great that you found a workaround for yours.
