### ISSUE TITLE
can we have an option to remap alt to control?

### ISSUE THREAD

**Issue by Fuseteam** [KabbAmine/vCoolor.vim#41]
i use alt to quickly execute normal commands in insert mode without the need to escape

**Comment by KabbAmine** [comment]
Hi, sorry for the late reply.

You can customize the mappings with `g:vcoolor_map` and other configuration variables.
Here I'm using `Control-c` for example:

```vim
let g:vcoolor_map = '<C-c>'
```

Check the included documentation:

```viml
:h vcoolor
:h vcoolor-mapping:custom
```
